// port-lint: source unicode_tables/perl_space.rs
// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED.
package io.github.kotlinmania.regexsyntax.unicodetables.perlspace

internal val WHITE_SPACE: Array<IntArray> = arrayOf(
    intArrayOf(9, 13),
    intArrayOf(32, 32),
    intArrayOf(133, 133),
    intArrayOf(160, 160),
    intArrayOf(5760, 5760),
    intArrayOf(8192, 8202),
    intArrayOf(8232, 8233),
    intArrayOf(8239, 8239),
    intArrayOf(8287, 8287),
    intArrayOf(12288, 12288),
)

internal val BY_NAME: Array<Pair<String, Array<IntArray>>> = arrayOf(
    "White_Space" to WHITE_SPACE,
)

