// port-lint: source unicode_tables/script.rs
// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED.
package io.github.kotlinmania.regexsyntax.unicodetables.script

internal val ADLAM: Array<IntArray> = arrayOf(
    intArrayOf(125184, 125259),
    intArrayOf(125264, 125273),
    intArrayOf(125278, 125279),
)

internal val AHOM: Array<IntArray> = arrayOf(
    intArrayOf(71424, 71450),
    intArrayOf(71453, 71467),
    intArrayOf(71472, 71494),
)

internal val ANATOLIAN_HIEROGLYPHS: Array<IntArray> = arrayOf(
    intArrayOf(82944, 83526),
)

internal val ARABIC: Array<IntArray> = arrayOf(
    intArrayOf(1536, 1540),
    intArrayOf(1542, 1547),
    intArrayOf(1549, 1562),
    intArrayOf(1564, 1566),
    intArrayOf(1568, 1599),
    intArrayOf(1601, 1610),
    intArrayOf(1622, 1647),
    intArrayOf(1649, 1756),
    intArrayOf(1758, 1791),
    intArrayOf(1872, 1919),
    intArrayOf(2160, 2190),
    intArrayOf(2192, 2193),
    intArrayOf(2199, 2273),
    intArrayOf(2275, 2303),
    intArrayOf(64336, 64450),
    intArrayOf(64467, 64829),
    intArrayOf(64832, 64911),
    intArrayOf(64914, 64967),
    intArrayOf(64975, 64975),
    intArrayOf(65008, 65023),
    intArrayOf(65136, 65140),
    intArrayOf(65142, 65276),
    intArrayOf(69216, 69246),
    intArrayOf(69314, 69316),
    intArrayOf(69372, 69375),
    intArrayOf(126464, 126467),
    intArrayOf(126469, 126495),
    intArrayOf(126497, 126498),
    intArrayOf(126500, 126500),
    intArrayOf(126503, 126503),
    intArrayOf(126505, 126514),
    intArrayOf(126516, 126519),
    intArrayOf(126521, 126521),
    intArrayOf(126523, 126523),
    intArrayOf(126530, 126530),
    intArrayOf(126535, 126535),
    intArrayOf(126537, 126537),
    intArrayOf(126539, 126539),
    intArrayOf(126541, 126543),
    intArrayOf(126545, 126546),
    intArrayOf(126548, 126548),
    intArrayOf(126551, 126551),
    intArrayOf(126553, 126553),
    intArrayOf(126555, 126555),
    intArrayOf(126557, 126557),
    intArrayOf(126559, 126559),
    intArrayOf(126561, 126562),
    intArrayOf(126564, 126564),
    intArrayOf(126567, 126570),
    intArrayOf(126572, 126578),
    intArrayOf(126580, 126583),
    intArrayOf(126585, 126588),
    intArrayOf(126590, 126590),
    intArrayOf(126592, 126601),
    intArrayOf(126603, 126619),
    intArrayOf(126625, 126627),
    intArrayOf(126629, 126633),
    intArrayOf(126635, 126651),
    intArrayOf(126704, 126705),
)

internal val ARMENIAN: Array<IntArray> = arrayOf(
    intArrayOf(1329, 1366),
    intArrayOf(1369, 1418),
    intArrayOf(1421, 1423),
    intArrayOf(64275, 64279),
)

internal val AVESTAN: Array<IntArray> = arrayOf(
    intArrayOf(68352, 68405),
    intArrayOf(68409, 68415),
)

internal val BALINESE: Array<IntArray> = arrayOf(
    intArrayOf(6912, 6988),
    intArrayOf(6990, 7039),
)

internal val BAMUM: Array<IntArray> = arrayOf(
    intArrayOf(42656, 42743),
    intArrayOf(92160, 92728),
)

internal val BASSA_VAH: Array<IntArray> = arrayOf(
    intArrayOf(92880, 92909),
    intArrayOf(92912, 92917),
)

internal val BATAK: Array<IntArray> = arrayOf(
    intArrayOf(7104, 7155),
    intArrayOf(7164, 7167),
)

internal val BENGALI: Array<IntArray> = arrayOf(
    intArrayOf(2432, 2435),
    intArrayOf(2437, 2444),
    intArrayOf(2447, 2448),
    intArrayOf(2451, 2472),
    intArrayOf(2474, 2480),
    intArrayOf(2482, 2482),
    intArrayOf(2486, 2489),
    intArrayOf(2492, 2500),
    intArrayOf(2503, 2504),
    intArrayOf(2507, 2510),
    intArrayOf(2519, 2519),
    intArrayOf(2524, 2525),
    intArrayOf(2527, 2531),
    intArrayOf(2534, 2558),
)

internal val BHAIKSUKI: Array<IntArray> = arrayOf(
    intArrayOf(72704, 72712),
    intArrayOf(72714, 72758),
    intArrayOf(72760, 72773),
    intArrayOf(72784, 72812),
)

internal val BOPOMOFO: Array<IntArray> = arrayOf(
    intArrayOf(746, 747),
    intArrayOf(12549, 12591),
    intArrayOf(12704, 12735),
)

internal val BRAHMI: Array<IntArray> = arrayOf(
    intArrayOf(69632, 69709),
    intArrayOf(69714, 69749),
    intArrayOf(69759, 69759),
)

internal val BRAILLE: Array<IntArray> = arrayOf(
    intArrayOf(10240, 10495),
)

internal val BUGINESE: Array<IntArray> = arrayOf(
    intArrayOf(6656, 6683),
    intArrayOf(6686, 6687),
)

internal val BUHID: Array<IntArray> = arrayOf(
    intArrayOf(5952, 5971),
)

internal val CANADIAN_ABORIGINAL: Array<IntArray> = arrayOf(
    intArrayOf(5120, 5759),
    intArrayOf(6320, 6389),
    intArrayOf(72368, 72383),
)

internal val CARIAN: Array<IntArray> = arrayOf(
    intArrayOf(66208, 66256),
)

internal val CAUCASIAN_ALBANIAN: Array<IntArray> = arrayOf(
    intArrayOf(66864, 66915),
    intArrayOf(66927, 66927),
)

internal val CHAKMA: Array<IntArray> = arrayOf(
    intArrayOf(69888, 69940),
    intArrayOf(69942, 69959),
)

internal val CHAM: Array<IntArray> = arrayOf(
    intArrayOf(43520, 43574),
    intArrayOf(43584, 43597),
    intArrayOf(43600, 43609),
    intArrayOf(43612, 43615),
)

internal val CHEROKEE: Array<IntArray> = arrayOf(
    intArrayOf(5024, 5109),
    intArrayOf(5112, 5117),
    intArrayOf(43888, 43967),
)

internal val CHORASMIAN: Array<IntArray> = arrayOf(
    intArrayOf(69552, 69579),
)

internal val COMMON: Array<IntArray> = arrayOf(
    intArrayOf(0, 64),
    intArrayOf(91, 96),
    intArrayOf(123, 169),
    intArrayOf(171, 185),
    intArrayOf(187, 191),
    intArrayOf(215, 215),
    intArrayOf(247, 247),
    intArrayOf(697, 735),
    intArrayOf(741, 745),
    intArrayOf(748, 767),
    intArrayOf(884, 884),
    intArrayOf(894, 894),
    intArrayOf(901, 901),
    intArrayOf(903, 903),
    intArrayOf(1541, 1541),
    intArrayOf(1548, 1548),
    intArrayOf(1563, 1563),
    intArrayOf(1567, 1567),
    intArrayOf(1600, 1600),
    intArrayOf(1757, 1757),
    intArrayOf(2274, 2274),
    intArrayOf(2404, 2405),
    intArrayOf(3647, 3647),
    intArrayOf(4053, 4056),
    intArrayOf(4347, 4347),
    intArrayOf(5867, 5869),
    intArrayOf(5941, 5942),
    intArrayOf(6146, 6147),
    intArrayOf(6149, 6149),
    intArrayOf(7379, 7379),
    intArrayOf(7393, 7393),
    intArrayOf(7401, 7404),
    intArrayOf(7406, 7411),
    intArrayOf(7413, 7415),
    intArrayOf(7418, 7418),
    intArrayOf(8192, 8203),
    intArrayOf(8206, 8292),
    intArrayOf(8294, 8304),
    intArrayOf(8308, 8318),
    intArrayOf(8320, 8334),
    intArrayOf(8352, 8384),
    intArrayOf(8448, 8485),
    intArrayOf(8487, 8489),
    intArrayOf(8492, 8497),
    intArrayOf(8499, 8525),
    intArrayOf(8527, 8543),
    intArrayOf(8585, 8587),
    intArrayOf(8592, 9257),
    intArrayOf(9280, 9290),
    intArrayOf(9312, 10239),
    intArrayOf(10496, 11123),
    intArrayOf(11126, 11157),
    intArrayOf(11159, 11263),
    intArrayOf(11776, 11869),
    intArrayOf(12272, 12292),
    intArrayOf(12294, 12294),
    intArrayOf(12296, 12320),
    intArrayOf(12336, 12343),
    intArrayOf(12348, 12351),
    intArrayOf(12443, 12444),
    intArrayOf(12448, 12448),
    intArrayOf(12539, 12540),
    intArrayOf(12688, 12703),
    intArrayOf(12736, 12773),
    intArrayOf(12783, 12783),
    intArrayOf(12832, 12895),
    intArrayOf(12927, 13007),
    intArrayOf(13055, 13055),
    intArrayOf(13144, 13311),
    intArrayOf(19904, 19967),
    intArrayOf(42752, 42785),
    intArrayOf(42888, 42890),
    intArrayOf(43056, 43065),
    intArrayOf(43310, 43310),
    intArrayOf(43471, 43471),
    intArrayOf(43867, 43867),
    intArrayOf(43882, 43883),
    intArrayOf(64830, 64831),
    intArrayOf(65040, 65049),
    intArrayOf(65072, 65106),
    intArrayOf(65108, 65126),
    intArrayOf(65128, 65131),
    intArrayOf(65279, 65279),
    intArrayOf(65281, 65312),
    intArrayOf(65339, 65344),
    intArrayOf(65371, 65381),
    intArrayOf(65392, 65392),
    intArrayOf(65438, 65439),
    intArrayOf(65504, 65510),
    intArrayOf(65512, 65518),
    intArrayOf(65529, 65533),
    intArrayOf(65792, 65794),
    intArrayOf(65799, 65843),
    intArrayOf(65847, 65855),
    intArrayOf(65936, 65948),
    intArrayOf(66000, 66044),
    intArrayOf(66273, 66299),
    intArrayOf(113824, 113827),
    intArrayOf(117760, 118009),
    intArrayOf(118016, 118451),
    intArrayOf(118608, 118723),
    intArrayOf(118784, 119029),
    intArrayOf(119040, 119078),
    intArrayOf(119081, 119142),
    intArrayOf(119146, 119162),
    intArrayOf(119171, 119172),
    intArrayOf(119180, 119209),
    intArrayOf(119214, 119274),
    intArrayOf(119488, 119507),
    intArrayOf(119520, 119539),
    intArrayOf(119552, 119638),
    intArrayOf(119648, 119672),
    intArrayOf(119808, 119892),
    intArrayOf(119894, 119964),
    intArrayOf(119966, 119967),
    intArrayOf(119970, 119970),
    intArrayOf(119973, 119974),
    intArrayOf(119977, 119980),
    intArrayOf(119982, 119993),
    intArrayOf(119995, 119995),
    intArrayOf(119997, 120003),
    intArrayOf(120005, 120069),
    intArrayOf(120071, 120074),
    intArrayOf(120077, 120084),
    intArrayOf(120086, 120092),
    intArrayOf(120094, 120121),
    intArrayOf(120123, 120126),
    intArrayOf(120128, 120132),
    intArrayOf(120134, 120134),
    intArrayOf(120138, 120144),
    intArrayOf(120146, 120485),
    intArrayOf(120488, 120779),
    intArrayOf(120782, 120831),
    intArrayOf(126065, 126132),
    intArrayOf(126209, 126269),
    intArrayOf(126976, 127019),
    intArrayOf(127024, 127123),
    intArrayOf(127136, 127150),
    intArrayOf(127153, 127167),
    intArrayOf(127169, 127183),
    intArrayOf(127185, 127221),
    intArrayOf(127232, 127405),
    intArrayOf(127462, 127487),
    intArrayOf(127489, 127490),
    intArrayOf(127504, 127547),
    intArrayOf(127552, 127560),
    intArrayOf(127568, 127569),
    intArrayOf(127584, 127589),
    intArrayOf(127744, 128727),
    intArrayOf(128732, 128748),
    intArrayOf(128752, 128764),
    intArrayOf(128768, 128886),
    intArrayOf(128891, 128985),
    intArrayOf(128992, 129003),
    intArrayOf(129008, 129008),
    intArrayOf(129024, 129035),
    intArrayOf(129040, 129095),
    intArrayOf(129104, 129113),
    intArrayOf(129120, 129159),
    intArrayOf(129168, 129197),
    intArrayOf(129200, 129211),
    intArrayOf(129216, 129217),
    intArrayOf(129280, 129619),
    intArrayOf(129632, 129645),
    intArrayOf(129648, 129660),
    intArrayOf(129664, 129673),
    intArrayOf(129679, 129734),
    intArrayOf(129742, 129756),
    intArrayOf(129759, 129769),
    intArrayOf(129776, 129784),
    intArrayOf(129792, 129938),
    intArrayOf(129940, 130041),
    intArrayOf(917505, 917505),
    intArrayOf(917536, 917631),
)

internal val COPTIC: Array<IntArray> = arrayOf(
    intArrayOf(994, 1007),
    intArrayOf(11392, 11507),
    intArrayOf(11513, 11519),
)

internal val CUNEIFORM: Array<IntArray> = arrayOf(
    intArrayOf(73728, 74649),
    intArrayOf(74752, 74862),
    intArrayOf(74864, 74868),
    intArrayOf(74880, 75075),
)

internal val CYPRIOT: Array<IntArray> = arrayOf(
    intArrayOf(67584, 67589),
    intArrayOf(67592, 67592),
    intArrayOf(67594, 67637),
    intArrayOf(67639, 67640),
    intArrayOf(67644, 67644),
    intArrayOf(67647, 67647),
)

internal val CYPRO_MINOAN: Array<IntArray> = arrayOf(
    intArrayOf(77712, 77810),
)

internal val CYRILLIC: Array<IntArray> = arrayOf(
    intArrayOf(1024, 1156),
    intArrayOf(1159, 1327),
    intArrayOf(7296, 7306),
    intArrayOf(7467, 7467),
    intArrayOf(7544, 7544),
    intArrayOf(11744, 11775),
    intArrayOf(42560, 42655),
    intArrayOf(65070, 65071),
    intArrayOf(122928, 122989),
    intArrayOf(123023, 123023),
)

internal val DESERET: Array<IntArray> = arrayOf(
    intArrayOf(66560, 66639),
)

internal val DEVANAGARI: Array<IntArray> = arrayOf(
    intArrayOf(2304, 2384),
    intArrayOf(2389, 2403),
    intArrayOf(2406, 2431),
    intArrayOf(43232, 43263),
    intArrayOf(72448, 72457),
)

internal val DIVES_AKURU: Array<IntArray> = arrayOf(
    intArrayOf(71936, 71942),
    intArrayOf(71945, 71945),
    intArrayOf(71948, 71955),
    intArrayOf(71957, 71958),
    intArrayOf(71960, 71989),
    intArrayOf(71991, 71992),
    intArrayOf(71995, 72006),
    intArrayOf(72016, 72025),
)

internal val DOGRA: Array<IntArray> = arrayOf(
    intArrayOf(71680, 71739),
)

internal val DUPLOYAN: Array<IntArray> = arrayOf(
    intArrayOf(113664, 113770),
    intArrayOf(113776, 113788),
    intArrayOf(113792, 113800),
    intArrayOf(113808, 113817),
    intArrayOf(113820, 113823),
)

internal val EGYPTIAN_HIEROGLYPHS: Array<IntArray> = arrayOf(
    intArrayOf(77824, 78933),
    intArrayOf(78944, 82938),
)

internal val ELBASAN: Array<IntArray> = arrayOf(
    intArrayOf(66816, 66855),
)

internal val ELYMAIC: Array<IntArray> = arrayOf(
    intArrayOf(69600, 69622),
)

internal val ETHIOPIC: Array<IntArray> = arrayOf(
    intArrayOf(4608, 4680),
    intArrayOf(4682, 4685),
    intArrayOf(4688, 4694),
    intArrayOf(4696, 4696),
    intArrayOf(4698, 4701),
    intArrayOf(4704, 4744),
    intArrayOf(4746, 4749),
    intArrayOf(4752, 4784),
    intArrayOf(4786, 4789),
    intArrayOf(4792, 4798),
    intArrayOf(4800, 4800),
    intArrayOf(4802, 4805),
    intArrayOf(4808, 4822),
    intArrayOf(4824, 4880),
    intArrayOf(4882, 4885),
    intArrayOf(4888, 4954),
    intArrayOf(4957, 4988),
    intArrayOf(4992, 5017),
    intArrayOf(11648, 11670),
    intArrayOf(11680, 11686),
    intArrayOf(11688, 11694),
    intArrayOf(11696, 11702),
    intArrayOf(11704, 11710),
    intArrayOf(11712, 11718),
    intArrayOf(11720, 11726),
    intArrayOf(11728, 11734),
    intArrayOf(11736, 11742),
    intArrayOf(43777, 43782),
    intArrayOf(43785, 43790),
    intArrayOf(43793, 43798),
    intArrayOf(43808, 43814),
    intArrayOf(43816, 43822),
    intArrayOf(124896, 124902),
    intArrayOf(124904, 124907),
    intArrayOf(124909, 124910),
    intArrayOf(124912, 124926),
)

internal val GARAY: Array<IntArray> = arrayOf(
    intArrayOf(68928, 68965),
    intArrayOf(68969, 68997),
    intArrayOf(69006, 69007),
)

internal val GEORGIAN: Array<IntArray> = arrayOf(
    intArrayOf(4256, 4293),
    intArrayOf(4295, 4295),
    intArrayOf(4301, 4301),
    intArrayOf(4304, 4346),
    intArrayOf(4348, 4351),
    intArrayOf(7312, 7354),
    intArrayOf(7357, 7359),
    intArrayOf(11520, 11557),
    intArrayOf(11559, 11559),
    intArrayOf(11565, 11565),
)

internal val GLAGOLITIC: Array<IntArray> = arrayOf(
    intArrayOf(11264, 11359),
    intArrayOf(122880, 122886),
    intArrayOf(122888, 122904),
    intArrayOf(122907, 122913),
    intArrayOf(122915, 122916),
    intArrayOf(122918, 122922),
)

internal val GOTHIC: Array<IntArray> = arrayOf(
    intArrayOf(66352, 66378),
)

internal val GRANTHA: Array<IntArray> = arrayOf(
    intArrayOf(70400, 70403),
    intArrayOf(70405, 70412),
    intArrayOf(70415, 70416),
    intArrayOf(70419, 70440),
    intArrayOf(70442, 70448),
    intArrayOf(70450, 70451),
    intArrayOf(70453, 70457),
    intArrayOf(70460, 70468),
    intArrayOf(70471, 70472),
    intArrayOf(70475, 70477),
    intArrayOf(70480, 70480),
    intArrayOf(70487, 70487),
    intArrayOf(70493, 70499),
    intArrayOf(70502, 70508),
    intArrayOf(70512, 70516),
)

internal val GREEK: Array<IntArray> = arrayOf(
    intArrayOf(880, 883),
    intArrayOf(885, 887),
    intArrayOf(890, 893),
    intArrayOf(895, 895),
    intArrayOf(900, 900),
    intArrayOf(902, 902),
    intArrayOf(904, 906),
    intArrayOf(908, 908),
    intArrayOf(910, 929),
    intArrayOf(931, 993),
    intArrayOf(1008, 1023),
    intArrayOf(7462, 7466),
    intArrayOf(7517, 7521),
    intArrayOf(7526, 7530),
    intArrayOf(7615, 7615),
    intArrayOf(7936, 7957),
    intArrayOf(7960, 7965),
    intArrayOf(7968, 8005),
    intArrayOf(8008, 8013),
    intArrayOf(8016, 8023),
    intArrayOf(8025, 8025),
    intArrayOf(8027, 8027),
    intArrayOf(8029, 8029),
    intArrayOf(8031, 8061),
    intArrayOf(8064, 8116),
    intArrayOf(8118, 8132),
    intArrayOf(8134, 8147),
    intArrayOf(8150, 8155),
    intArrayOf(8157, 8175),
    intArrayOf(8178, 8180),
    intArrayOf(8182, 8190),
    intArrayOf(8486, 8486),
    intArrayOf(43877, 43877),
    intArrayOf(65856, 65934),
    intArrayOf(65952, 65952),
    intArrayOf(119296, 119365),
)

internal val GUJARATI: Array<IntArray> = arrayOf(
    intArrayOf(2689, 2691),
    intArrayOf(2693, 2701),
    intArrayOf(2703, 2705),
    intArrayOf(2707, 2728),
    intArrayOf(2730, 2736),
    intArrayOf(2738, 2739),
    intArrayOf(2741, 2745),
    intArrayOf(2748, 2757),
    intArrayOf(2759, 2761),
    intArrayOf(2763, 2765),
    intArrayOf(2768, 2768),
    intArrayOf(2784, 2787),
    intArrayOf(2790, 2801),
    intArrayOf(2809, 2815),
)

internal val GUNJALA_GONDI: Array<IntArray> = arrayOf(
    intArrayOf(73056, 73061),
    intArrayOf(73063, 73064),
    intArrayOf(73066, 73102),
    intArrayOf(73104, 73105),
    intArrayOf(73107, 73112),
    intArrayOf(73120, 73129),
)

internal val GURMUKHI: Array<IntArray> = arrayOf(
    intArrayOf(2561, 2563),
    intArrayOf(2565, 2570),
    intArrayOf(2575, 2576),
    intArrayOf(2579, 2600),
    intArrayOf(2602, 2608),
    intArrayOf(2610, 2611),
    intArrayOf(2613, 2614),
    intArrayOf(2616, 2617),
    intArrayOf(2620, 2620),
    intArrayOf(2622, 2626),
    intArrayOf(2631, 2632),
    intArrayOf(2635, 2637),
    intArrayOf(2641, 2641),
    intArrayOf(2649, 2652),
    intArrayOf(2654, 2654),
    intArrayOf(2662, 2678),
)

internal val GURUNG_KHEMA: Array<IntArray> = arrayOf(
    intArrayOf(90368, 90425),
)

internal val HAN: Array<IntArray> = arrayOf(
    intArrayOf(11904, 11929),
    intArrayOf(11931, 12019),
    intArrayOf(12032, 12245),
    intArrayOf(12293, 12293),
    intArrayOf(12295, 12295),
    intArrayOf(12321, 12329),
    intArrayOf(12344, 12347),
    intArrayOf(13312, 19903),
    intArrayOf(19968, 40959),
    intArrayOf(63744, 64109),
    intArrayOf(64112, 64217),
    intArrayOf(94178, 94179),
    intArrayOf(94192, 94193),
    intArrayOf(131072, 173791),
    intArrayOf(173824, 177977),
    intArrayOf(177984, 178205),
    intArrayOf(178208, 183969),
    intArrayOf(183984, 191456),
    intArrayOf(191472, 192093),
    intArrayOf(194560, 195101),
    intArrayOf(196608, 201546),
    intArrayOf(201552, 205743),
)

internal val HANGUL: Array<IntArray> = arrayOf(
    intArrayOf(4352, 4607),
    intArrayOf(12334, 12335),
    intArrayOf(12593, 12686),
    intArrayOf(12800, 12830),
    intArrayOf(12896, 12926),
    intArrayOf(43360, 43388),
    intArrayOf(44032, 55203),
    intArrayOf(55216, 55238),
    intArrayOf(55243, 55291),
    intArrayOf(65440, 65470),
    intArrayOf(65474, 65479),
    intArrayOf(65482, 65487),
    intArrayOf(65490, 65495),
    intArrayOf(65498, 65500),
)

internal val HANIFI_ROHINGYA: Array<IntArray> = arrayOf(
    intArrayOf(68864, 68903),
    intArrayOf(68912, 68921),
)

internal val HANUNOO: Array<IntArray> = arrayOf(
    intArrayOf(5920, 5940),
)

internal val HATRAN: Array<IntArray> = arrayOf(
    intArrayOf(67808, 67826),
    intArrayOf(67828, 67829),
    intArrayOf(67835, 67839),
)

internal val HEBREW: Array<IntArray> = arrayOf(
    intArrayOf(1425, 1479),
    intArrayOf(1488, 1514),
    intArrayOf(1519, 1524),
    intArrayOf(64285, 64310),
    intArrayOf(64312, 64316),
    intArrayOf(64318, 64318),
    intArrayOf(64320, 64321),
    intArrayOf(64323, 64324),
    intArrayOf(64326, 64335),
)

internal val HIRAGANA: Array<IntArray> = arrayOf(
    intArrayOf(12353, 12438),
    intArrayOf(12445, 12447),
    intArrayOf(110593, 110879),
    intArrayOf(110898, 110898),
    intArrayOf(110928, 110930),
    intArrayOf(127488, 127488),
)

internal val IMPERIAL_ARAMAIC: Array<IntArray> = arrayOf(
    intArrayOf(67648, 67669),
    intArrayOf(67671, 67679),
)

internal val INHERITED: Array<IntArray> = arrayOf(
    intArrayOf(768, 879),
    intArrayOf(1157, 1158),
    intArrayOf(1611, 1621),
    intArrayOf(1648, 1648),
    intArrayOf(2385, 2388),
    intArrayOf(6832, 6862),
    intArrayOf(7376, 7378),
    intArrayOf(7380, 7392),
    intArrayOf(7394, 7400),
    intArrayOf(7405, 7405),
    intArrayOf(7412, 7412),
    intArrayOf(7416, 7417),
    intArrayOf(7616, 7679),
    intArrayOf(8204, 8205),
    intArrayOf(8400, 8432),
    intArrayOf(12330, 12333),
    intArrayOf(12441, 12442),
    intArrayOf(65024, 65039),
    intArrayOf(65056, 65069),
    intArrayOf(66045, 66045),
    intArrayOf(66272, 66272),
    intArrayOf(70459, 70459),
    intArrayOf(118528, 118573),
    intArrayOf(118576, 118598),
    intArrayOf(119143, 119145),
    intArrayOf(119163, 119170),
    intArrayOf(119173, 119179),
    intArrayOf(119210, 119213),
    intArrayOf(917760, 917999),
)

internal val INSCRIPTIONAL_PAHLAVI: Array<IntArray> = arrayOf(
    intArrayOf(68448, 68466),
    intArrayOf(68472, 68479),
)

internal val INSCRIPTIONAL_PARTHIAN: Array<IntArray> = arrayOf(
    intArrayOf(68416, 68437),
    intArrayOf(68440, 68447),
)

internal val JAVANESE: Array<IntArray> = arrayOf(
    intArrayOf(43392, 43469),
    intArrayOf(43472, 43481),
    intArrayOf(43486, 43487),
)

internal val KAITHI: Array<IntArray> = arrayOf(
    intArrayOf(69760, 69826),
    intArrayOf(69837, 69837),
)

internal val KANNADA: Array<IntArray> = arrayOf(
    intArrayOf(3200, 3212),
    intArrayOf(3214, 3216),
    intArrayOf(3218, 3240),
    intArrayOf(3242, 3251),
    intArrayOf(3253, 3257),
    intArrayOf(3260, 3268),
    intArrayOf(3270, 3272),
    intArrayOf(3274, 3277),
    intArrayOf(3285, 3286),
    intArrayOf(3293, 3294),
    intArrayOf(3296, 3299),
    intArrayOf(3302, 3311),
    intArrayOf(3313, 3315),
)

internal val KATAKANA: Array<IntArray> = arrayOf(
    intArrayOf(12449, 12538),
    intArrayOf(12541, 12543),
    intArrayOf(12784, 12799),
    intArrayOf(13008, 13054),
    intArrayOf(13056, 13143),
    intArrayOf(65382, 65391),
    intArrayOf(65393, 65437),
    intArrayOf(110576, 110579),
    intArrayOf(110581, 110587),
    intArrayOf(110589, 110590),
    intArrayOf(110592, 110592),
    intArrayOf(110880, 110882),
    intArrayOf(110933, 110933),
    intArrayOf(110948, 110951),
)

internal val KAWI: Array<IntArray> = arrayOf(
    intArrayOf(73472, 73488),
    intArrayOf(73490, 73530),
    intArrayOf(73534, 73562),
)

internal val KAYAH_LI: Array<IntArray> = arrayOf(
    intArrayOf(43264, 43309),
    intArrayOf(43311, 43311),
)

internal val KHAROSHTHI: Array<IntArray> = arrayOf(
    intArrayOf(68096, 68099),
    intArrayOf(68101, 68102),
    intArrayOf(68108, 68115),
    intArrayOf(68117, 68119),
    intArrayOf(68121, 68149),
    intArrayOf(68152, 68154),
    intArrayOf(68159, 68168),
    intArrayOf(68176, 68184),
)

internal val KHITAN_SMALL_SCRIPT: Array<IntArray> = arrayOf(
    intArrayOf(94180, 94180),
    intArrayOf(101120, 101589),
    intArrayOf(101631, 101631),
)

internal val KHMER: Array<IntArray> = arrayOf(
    intArrayOf(6016, 6109),
    intArrayOf(6112, 6121),
    intArrayOf(6128, 6137),
    intArrayOf(6624, 6655),
)

internal val KHOJKI: Array<IntArray> = arrayOf(
    intArrayOf(70144, 70161),
    intArrayOf(70163, 70209),
)

internal val KHUDAWADI: Array<IntArray> = arrayOf(
    intArrayOf(70320, 70378),
    intArrayOf(70384, 70393),
)

internal val KIRAT_RAI: Array<IntArray> = arrayOf(
    intArrayOf(93504, 93561),
)

internal val LAO: Array<IntArray> = arrayOf(
    intArrayOf(3713, 3714),
    intArrayOf(3716, 3716),
    intArrayOf(3718, 3722),
    intArrayOf(3724, 3747),
    intArrayOf(3749, 3749),
    intArrayOf(3751, 3773),
    intArrayOf(3776, 3780),
    intArrayOf(3782, 3782),
    intArrayOf(3784, 3790),
    intArrayOf(3792, 3801),
    intArrayOf(3804, 3807),
)

internal val LATIN: Array<IntArray> = arrayOf(
    intArrayOf(65, 90),
    intArrayOf(97, 122),
    intArrayOf(170, 170),
    intArrayOf(186, 186),
    intArrayOf(192, 214),
    intArrayOf(216, 246),
    intArrayOf(248, 696),
    intArrayOf(736, 740),
    intArrayOf(7424, 7461),
    intArrayOf(7468, 7516),
    intArrayOf(7522, 7525),
    intArrayOf(7531, 7543),
    intArrayOf(7545, 7614),
    intArrayOf(7680, 7935),
    intArrayOf(8305, 8305),
    intArrayOf(8319, 8319),
    intArrayOf(8336, 8348),
    intArrayOf(8490, 8491),
    intArrayOf(8498, 8498),
    intArrayOf(8526, 8526),
    intArrayOf(8544, 8584),
    intArrayOf(11360, 11391),
    intArrayOf(42786, 42887),
    intArrayOf(42891, 42957),
    intArrayOf(42960, 42961),
    intArrayOf(42963, 42963),
    intArrayOf(42965, 42972),
    intArrayOf(42994, 43007),
    intArrayOf(43824, 43866),
    intArrayOf(43868, 43876),
    intArrayOf(43878, 43881),
    intArrayOf(64256, 64262),
    intArrayOf(65313, 65338),
    intArrayOf(65345, 65370),
    intArrayOf(67456, 67461),
    intArrayOf(67463, 67504),
    intArrayOf(67506, 67514),
    intArrayOf(122624, 122654),
    intArrayOf(122661, 122666),
)

internal val LEPCHA: Array<IntArray> = arrayOf(
    intArrayOf(7168, 7223),
    intArrayOf(7227, 7241),
    intArrayOf(7245, 7247),
)

internal val LIMBU: Array<IntArray> = arrayOf(
    intArrayOf(6400, 6430),
    intArrayOf(6432, 6443),
    intArrayOf(6448, 6459),
    intArrayOf(6464, 6464),
    intArrayOf(6468, 6479),
)

internal val LINEAR_A: Array<IntArray> = arrayOf(
    intArrayOf(67072, 67382),
    intArrayOf(67392, 67413),
    intArrayOf(67424, 67431),
)

internal val LINEAR_B: Array<IntArray> = arrayOf(
    intArrayOf(65536, 65547),
    intArrayOf(65549, 65574),
    intArrayOf(65576, 65594),
    intArrayOf(65596, 65597),
    intArrayOf(65599, 65613),
    intArrayOf(65616, 65629),
    intArrayOf(65664, 65786),
)

internal val LISU: Array<IntArray> = arrayOf(
    intArrayOf(42192, 42239),
    intArrayOf(73648, 73648),
)

internal val LYCIAN: Array<IntArray> = arrayOf(
    intArrayOf(66176, 66204),
)

internal val LYDIAN: Array<IntArray> = arrayOf(
    intArrayOf(67872, 67897),
    intArrayOf(67903, 67903),
)

internal val MAHAJANI: Array<IntArray> = arrayOf(
    intArrayOf(69968, 70006),
)

internal val MAKASAR: Array<IntArray> = arrayOf(
    intArrayOf(73440, 73464),
)

internal val MALAYALAM: Array<IntArray> = arrayOf(
    intArrayOf(3328, 3340),
    intArrayOf(3342, 3344),
    intArrayOf(3346, 3396),
    intArrayOf(3398, 3400),
    intArrayOf(3402, 3407),
    intArrayOf(3412, 3427),
    intArrayOf(3430, 3455),
)

internal val MANDAIC: Array<IntArray> = arrayOf(
    intArrayOf(2112, 2139),
    intArrayOf(2142, 2142),
)

internal val MANICHAEAN: Array<IntArray> = arrayOf(
    intArrayOf(68288, 68326),
    intArrayOf(68331, 68342),
)

internal val MARCHEN: Array<IntArray> = arrayOf(
    intArrayOf(72816, 72847),
    intArrayOf(72850, 72871),
    intArrayOf(72873, 72886),
)

internal val MASARAM_GONDI: Array<IntArray> = arrayOf(
    intArrayOf(72960, 72966),
    intArrayOf(72968, 72969),
    intArrayOf(72971, 73014),
    intArrayOf(73018, 73018),
    intArrayOf(73020, 73021),
    intArrayOf(73023, 73031),
    intArrayOf(73040, 73049),
)

internal val MEDEFAIDRIN: Array<IntArray> = arrayOf(
    intArrayOf(93760, 93850),
)

internal val MEETEI_MAYEK: Array<IntArray> = arrayOf(
    intArrayOf(43744, 43766),
    intArrayOf(43968, 44013),
    intArrayOf(44016, 44025),
)

internal val MENDE_KIKAKUI: Array<IntArray> = arrayOf(
    intArrayOf(124928, 125124),
    intArrayOf(125127, 125142),
)

internal val MEROITIC_CURSIVE: Array<IntArray> = arrayOf(
    intArrayOf(68000, 68023),
    intArrayOf(68028, 68047),
    intArrayOf(68050, 68095),
)

internal val MEROITIC_HIEROGLYPHS: Array<IntArray> = arrayOf(
    intArrayOf(67968, 67999),
)

internal val MIAO: Array<IntArray> = arrayOf(
    intArrayOf(93952, 94026),
    intArrayOf(94031, 94087),
    intArrayOf(94095, 94111),
)

internal val MODI: Array<IntArray> = arrayOf(
    intArrayOf(71168, 71236),
    intArrayOf(71248, 71257),
)

internal val MONGOLIAN: Array<IntArray> = arrayOf(
    intArrayOf(6144, 6145),
    intArrayOf(6148, 6148),
    intArrayOf(6150, 6169),
    intArrayOf(6176, 6264),
    intArrayOf(6272, 6314),
    intArrayOf(71264, 71276),
)

internal val MRO: Array<IntArray> = arrayOf(
    intArrayOf(92736, 92766),
    intArrayOf(92768, 92777),
    intArrayOf(92782, 92783),
)

internal val MULTANI: Array<IntArray> = arrayOf(
    intArrayOf(70272, 70278),
    intArrayOf(70280, 70280),
    intArrayOf(70282, 70285),
    intArrayOf(70287, 70301),
    intArrayOf(70303, 70313),
)

internal val MYANMAR: Array<IntArray> = arrayOf(
    intArrayOf(4096, 4255),
    intArrayOf(43488, 43518),
    intArrayOf(43616, 43647),
    intArrayOf(71376, 71395),
)

internal val NABATAEAN: Array<IntArray> = arrayOf(
    intArrayOf(67712, 67742),
    intArrayOf(67751, 67759),
)

internal val NAG_MUNDARI: Array<IntArray> = arrayOf(
    intArrayOf(124112, 124153),
)

internal val NANDINAGARI: Array<IntArray> = arrayOf(
    intArrayOf(72096, 72103),
    intArrayOf(72106, 72151),
    intArrayOf(72154, 72164),
)

internal val NEW_TAI_LUE: Array<IntArray> = arrayOf(
    intArrayOf(6528, 6571),
    intArrayOf(6576, 6601),
    intArrayOf(6608, 6618),
    intArrayOf(6622, 6623),
)

internal val NEWA: Array<IntArray> = arrayOf(
    intArrayOf(70656, 70747),
    intArrayOf(70749, 70753),
)

internal val NKO: Array<IntArray> = arrayOf(
    intArrayOf(1984, 2042),
    intArrayOf(2045, 2047),
)

internal val NUSHU: Array<IntArray> = arrayOf(
    intArrayOf(94177, 94177),
    intArrayOf(110960, 111355),
)

internal val NYIAKENG_PUACHUE_HMONG: Array<IntArray> = arrayOf(
    intArrayOf(123136, 123180),
    intArrayOf(123184, 123197),
    intArrayOf(123200, 123209),
    intArrayOf(123214, 123215),
)

internal val OGHAM: Array<IntArray> = arrayOf(
    intArrayOf(5760, 5788),
)

internal val OL_CHIKI: Array<IntArray> = arrayOf(
    intArrayOf(7248, 7295),
)

internal val OL_ONAL: Array<IntArray> = arrayOf(
    intArrayOf(124368, 124410),
    intArrayOf(124415, 124415),
)

internal val OLD_HUNGARIAN: Array<IntArray> = arrayOf(
    intArrayOf(68736, 68786),
    intArrayOf(68800, 68850),
    intArrayOf(68858, 68863),
)

internal val OLD_ITALIC: Array<IntArray> = arrayOf(
    intArrayOf(66304, 66339),
    intArrayOf(66349, 66351),
)

internal val OLD_NORTH_ARABIAN: Array<IntArray> = arrayOf(
    intArrayOf(68224, 68255),
)

internal val OLD_PERMIC: Array<IntArray> = arrayOf(
    intArrayOf(66384, 66426),
)

internal val OLD_PERSIAN: Array<IntArray> = arrayOf(
    intArrayOf(66464, 66499),
    intArrayOf(66504, 66517),
)

internal val OLD_SOGDIAN: Array<IntArray> = arrayOf(
    intArrayOf(69376, 69415),
)

internal val OLD_SOUTH_ARABIAN: Array<IntArray> = arrayOf(
    intArrayOf(68192, 68223),
)

internal val OLD_TURKIC: Array<IntArray> = arrayOf(
    intArrayOf(68608, 68680),
)

internal val OLD_UYGHUR: Array<IntArray> = arrayOf(
    intArrayOf(69488, 69513),
)

internal val ORIYA: Array<IntArray> = arrayOf(
    intArrayOf(2817, 2819),
    intArrayOf(2821, 2828),
    intArrayOf(2831, 2832),
    intArrayOf(2835, 2856),
    intArrayOf(2858, 2864),
    intArrayOf(2866, 2867),
    intArrayOf(2869, 2873),
    intArrayOf(2876, 2884),
    intArrayOf(2887, 2888),
    intArrayOf(2891, 2893),
    intArrayOf(2901, 2903),
    intArrayOf(2908, 2909),
    intArrayOf(2911, 2915),
    intArrayOf(2918, 2935),
)

internal val OSAGE: Array<IntArray> = arrayOf(
    intArrayOf(66736, 66771),
    intArrayOf(66776, 66811),
)

internal val OSMANYA: Array<IntArray> = arrayOf(
    intArrayOf(66688, 66717),
    intArrayOf(66720, 66729),
)

internal val PAHAWH_HMONG: Array<IntArray> = arrayOf(
    intArrayOf(92928, 92997),
    intArrayOf(93008, 93017),
    intArrayOf(93019, 93025),
    intArrayOf(93027, 93047),
    intArrayOf(93053, 93071),
)

internal val PALMYRENE: Array<IntArray> = arrayOf(
    intArrayOf(67680, 67711),
)

internal val PAU_CIN_HAU: Array<IntArray> = arrayOf(
    intArrayOf(72384, 72440),
)

internal val PHAGS_PA: Array<IntArray> = arrayOf(
    intArrayOf(43072, 43127),
)

internal val PHOENICIAN: Array<IntArray> = arrayOf(
    intArrayOf(67840, 67867),
    intArrayOf(67871, 67871),
)

internal val PSALTER_PAHLAVI: Array<IntArray> = arrayOf(
    intArrayOf(68480, 68497),
    intArrayOf(68505, 68508),
    intArrayOf(68521, 68527),
)

internal val REJANG: Array<IntArray> = arrayOf(
    intArrayOf(43312, 43347),
    intArrayOf(43359, 43359),
)

internal val RUNIC: Array<IntArray> = arrayOf(
    intArrayOf(5792, 5866),
    intArrayOf(5870, 5880),
)

internal val SAMARITAN: Array<IntArray> = arrayOf(
    intArrayOf(2048, 2093),
    intArrayOf(2096, 2110),
)

internal val SAURASHTRA: Array<IntArray> = arrayOf(
    intArrayOf(43136, 43205),
    intArrayOf(43214, 43225),
)

internal val SHARADA: Array<IntArray> = arrayOf(
    intArrayOf(70016, 70111),
)

internal val SHAVIAN: Array<IntArray> = arrayOf(
    intArrayOf(66640, 66687),
)

internal val SIDDHAM: Array<IntArray> = arrayOf(
    intArrayOf(71040, 71093),
    intArrayOf(71096, 71133),
)

internal val SIGNWRITING: Array<IntArray> = arrayOf(
    intArrayOf(120832, 121483),
    intArrayOf(121499, 121503),
    intArrayOf(121505, 121519),
)

internal val SINHALA: Array<IntArray> = arrayOf(
    intArrayOf(3457, 3459),
    intArrayOf(3461, 3478),
    intArrayOf(3482, 3505),
    intArrayOf(3507, 3515),
    intArrayOf(3517, 3517),
    intArrayOf(3520, 3526),
    intArrayOf(3530, 3530),
    intArrayOf(3535, 3540),
    intArrayOf(3542, 3542),
    intArrayOf(3544, 3551),
    intArrayOf(3558, 3567),
    intArrayOf(3570, 3572),
    intArrayOf(70113, 70132),
)

internal val SOGDIAN: Array<IntArray> = arrayOf(
    intArrayOf(69424, 69465),
)

internal val SORA_SOMPENG: Array<IntArray> = arrayOf(
    intArrayOf(69840, 69864),
    intArrayOf(69872, 69881),
)

internal val SOYOMBO: Array<IntArray> = arrayOf(
    intArrayOf(72272, 72354),
)

internal val SUNDANESE: Array<IntArray> = arrayOf(
    intArrayOf(7040, 7103),
    intArrayOf(7360, 7367),
)

internal val SUNUWAR: Array<IntArray> = arrayOf(
    intArrayOf(72640, 72673),
    intArrayOf(72688, 72697),
)

internal val SYLOTI_NAGRI: Array<IntArray> = arrayOf(
    intArrayOf(43008, 43052),
)

internal val SYRIAC: Array<IntArray> = arrayOf(
    intArrayOf(1792, 1805),
    intArrayOf(1807, 1866),
    intArrayOf(1869, 1871),
    intArrayOf(2144, 2154),
)

internal val TAGALOG: Array<IntArray> = arrayOf(
    intArrayOf(5888, 5909),
    intArrayOf(5919, 5919),
)

internal val TAGBANWA: Array<IntArray> = arrayOf(
    intArrayOf(5984, 5996),
    intArrayOf(5998, 6000),
    intArrayOf(6002, 6003),
)

internal val TAI_LE: Array<IntArray> = arrayOf(
    intArrayOf(6480, 6509),
    intArrayOf(6512, 6516),
)

internal val TAI_THAM: Array<IntArray> = arrayOf(
    intArrayOf(6688, 6750),
    intArrayOf(6752, 6780),
    intArrayOf(6783, 6793),
    intArrayOf(6800, 6809),
    intArrayOf(6816, 6829),
)

internal val TAI_VIET: Array<IntArray> = arrayOf(
    intArrayOf(43648, 43714),
    intArrayOf(43739, 43743),
)

internal val TAKRI: Array<IntArray> = arrayOf(
    intArrayOf(71296, 71353),
    intArrayOf(71360, 71369),
)

internal val TAMIL: Array<IntArray> = arrayOf(
    intArrayOf(2946, 2947),
    intArrayOf(2949, 2954),
    intArrayOf(2958, 2960),
    intArrayOf(2962, 2965),
    intArrayOf(2969, 2970),
    intArrayOf(2972, 2972),
    intArrayOf(2974, 2975),
    intArrayOf(2979, 2980),
    intArrayOf(2984, 2986),
    intArrayOf(2990, 3001),
    intArrayOf(3006, 3010),
    intArrayOf(3014, 3016),
    intArrayOf(3018, 3021),
    intArrayOf(3024, 3024),
    intArrayOf(3031, 3031),
    intArrayOf(3046, 3066),
    intArrayOf(73664, 73713),
    intArrayOf(73727, 73727),
)

internal val TANGSA: Array<IntArray> = arrayOf(
    intArrayOf(92784, 92862),
    intArrayOf(92864, 92873),
)

internal val TANGUT: Array<IntArray> = arrayOf(
    intArrayOf(94176, 94176),
    intArrayOf(94208, 100343),
    intArrayOf(100352, 101119),
    intArrayOf(101632, 101640),
)

internal val TELUGU: Array<IntArray> = arrayOf(
    intArrayOf(3072, 3084),
    intArrayOf(3086, 3088),
    intArrayOf(3090, 3112),
    intArrayOf(3114, 3129),
    intArrayOf(3132, 3140),
    intArrayOf(3142, 3144),
    intArrayOf(3146, 3149),
    intArrayOf(3157, 3158),
    intArrayOf(3160, 3162),
    intArrayOf(3165, 3165),
    intArrayOf(3168, 3171),
    intArrayOf(3174, 3183),
    intArrayOf(3191, 3199),
)

internal val THAANA: Array<IntArray> = arrayOf(
    intArrayOf(1920, 1969),
)

internal val THAI: Array<IntArray> = arrayOf(
    intArrayOf(3585, 3642),
    intArrayOf(3648, 3675),
)

internal val TIBETAN: Array<IntArray> = arrayOf(
    intArrayOf(3840, 3911),
    intArrayOf(3913, 3948),
    intArrayOf(3953, 3991),
    intArrayOf(3993, 4028),
    intArrayOf(4030, 4044),
    intArrayOf(4046, 4052),
    intArrayOf(4057, 4058),
)

internal val TIFINAGH: Array<IntArray> = arrayOf(
    intArrayOf(11568, 11623),
    intArrayOf(11631, 11632),
    intArrayOf(11647, 11647),
)

internal val TIRHUTA: Array<IntArray> = arrayOf(
    intArrayOf(70784, 70855),
    intArrayOf(70864, 70873),
)

internal val TODHRI: Array<IntArray> = arrayOf(
    intArrayOf(67008, 67059),
)

internal val TOTO: Array<IntArray> = arrayOf(
    intArrayOf(123536, 123566),
)

internal val TULU_TIGALARI: Array<IntArray> = arrayOf(
    intArrayOf(70528, 70537),
    intArrayOf(70539, 70539),
    intArrayOf(70542, 70542),
    intArrayOf(70544, 70581),
    intArrayOf(70583, 70592),
    intArrayOf(70594, 70594),
    intArrayOf(70597, 70597),
    intArrayOf(70599, 70602),
    intArrayOf(70604, 70613),
    intArrayOf(70615, 70616),
    intArrayOf(70625, 70626),
)

internal val UGARITIC: Array<IntArray> = arrayOf(
    intArrayOf(66432, 66461),
    intArrayOf(66463, 66463),
)

internal val VAI: Array<IntArray> = arrayOf(
    intArrayOf(42240, 42539),
)

internal val VITHKUQI: Array<IntArray> = arrayOf(
    intArrayOf(66928, 66938),
    intArrayOf(66940, 66954),
    intArrayOf(66956, 66962),
    intArrayOf(66964, 66965),
    intArrayOf(66967, 66977),
    intArrayOf(66979, 66993),
    intArrayOf(66995, 67001),
    intArrayOf(67003, 67004),
)

internal val WANCHO: Array<IntArray> = arrayOf(
    intArrayOf(123584, 123641),
    intArrayOf(123647, 123647),
)

internal val WARANG_CITI: Array<IntArray> = arrayOf(
    intArrayOf(71840, 71922),
    intArrayOf(71935, 71935),
)

internal val YEZIDI: Array<IntArray> = arrayOf(
    intArrayOf(69248, 69289),
    intArrayOf(69291, 69293),
    intArrayOf(69296, 69297),
)

internal val YI: Array<IntArray> = arrayOf(
    intArrayOf(40960, 42124),
    intArrayOf(42128, 42182),
)

internal val ZANABAZAR_SQUARE: Array<IntArray> = arrayOf(
    intArrayOf(72192, 72263),
)

internal val BY_NAME: Array<Pair<String, Array<IntArray>>> = arrayOf(
    "Adlam" to ADLAM,
    "Ahom" to AHOM,
    "Anatolian_Hieroglyphs" to ANATOLIAN_HIEROGLYPHS,
    "Arabic" to ARABIC,
    "Armenian" to ARMENIAN,
    "Avestan" to AVESTAN,
    "Balinese" to BALINESE,
    "Bamum" to BAMUM,
    "Bassa_Vah" to BASSA_VAH,
    "Batak" to BATAK,
    "Bengali" to BENGALI,
    "Bhaiksuki" to BHAIKSUKI,
    "Bopomofo" to BOPOMOFO,
    "Brahmi" to BRAHMI,
    "Braille" to BRAILLE,
    "Buginese" to BUGINESE,
    "Buhid" to BUHID,
    "Canadian_Aboriginal" to CANADIAN_ABORIGINAL,
    "Carian" to CARIAN,
    "Caucasian_Albanian" to CAUCASIAN_ALBANIAN,
    "Chakma" to CHAKMA,
    "Cham" to CHAM,
    "Cherokee" to CHEROKEE,
    "Chorasmian" to CHORASMIAN,
    "Common" to COMMON,
    "Coptic" to COPTIC,
    "Cuneiform" to CUNEIFORM,
    "Cypriot" to CYPRIOT,
    "Cypro_Minoan" to CYPRO_MINOAN,
    "Cyrillic" to CYRILLIC,
    "Deseret" to DESERET,
    "Devanagari" to DEVANAGARI,
    "Dives_Akuru" to DIVES_AKURU,
    "Dogra" to DOGRA,
    "Duployan" to DUPLOYAN,
    "Egyptian_Hieroglyphs" to EGYPTIAN_HIEROGLYPHS,
    "Elbasan" to ELBASAN,
    "Elymaic" to ELYMAIC,
    "Ethiopic" to ETHIOPIC,
    "Garay" to GARAY,
    "Georgian" to GEORGIAN,
    "Glagolitic" to GLAGOLITIC,
    "Gothic" to GOTHIC,
    "Grantha" to GRANTHA,
    "Greek" to GREEK,
    "Gujarati" to GUJARATI,
    "Gunjala_Gondi" to GUNJALA_GONDI,
    "Gurmukhi" to GURMUKHI,
    "Gurung_Khema" to GURUNG_KHEMA,
    "Han" to HAN,
    "Hangul" to HANGUL,
    "Hanifi_Rohingya" to HANIFI_ROHINGYA,
    "Hanunoo" to HANUNOO,
    "Hatran" to HATRAN,
    "Hebrew" to HEBREW,
    "Hiragana" to HIRAGANA,
    "Imperial_Aramaic" to IMPERIAL_ARAMAIC,
    "Inherited" to INHERITED,
    "Inscriptional_Pahlavi" to INSCRIPTIONAL_PAHLAVI,
    "Inscriptional_Parthian" to INSCRIPTIONAL_PARTHIAN,
    "Javanese" to JAVANESE,
    "Kaithi" to KAITHI,
    "Kannada" to KANNADA,
    "Katakana" to KATAKANA,
    "Kawi" to KAWI,
    "Kayah_Li" to KAYAH_LI,
    "Kharoshthi" to KHAROSHTHI,
    "Khitan_Small_Script" to KHITAN_SMALL_SCRIPT,
    "Khmer" to KHMER,
    "Khojki" to KHOJKI,
    "Khudawadi" to KHUDAWADI,
    "Kirat_Rai" to KIRAT_RAI,
    "Lao" to LAO,
    "Latin" to LATIN,
    "Lepcha" to LEPCHA,
    "Limbu" to LIMBU,
    "Linear_A" to LINEAR_A,
    "Linear_B" to LINEAR_B,
    "Lisu" to LISU,
    "Lycian" to LYCIAN,
    "Lydian" to LYDIAN,
    "Mahajani" to MAHAJANI,
    "Makasar" to MAKASAR,
    "Malayalam" to MALAYALAM,
    "Mandaic" to MANDAIC,
    "Manichaean" to MANICHAEAN,
    "Marchen" to MARCHEN,
    "Masaram_Gondi" to MASARAM_GONDI,
    "Medefaidrin" to MEDEFAIDRIN,
    "Meetei_Mayek" to MEETEI_MAYEK,
    "Mende_Kikakui" to MENDE_KIKAKUI,
    "Meroitic_Cursive" to MEROITIC_CURSIVE,
    "Meroitic_Hieroglyphs" to MEROITIC_HIEROGLYPHS,
    "Miao" to MIAO,
    "Modi" to MODI,
    "Mongolian" to MONGOLIAN,
    "Mro" to MRO,
    "Multani" to MULTANI,
    "Myanmar" to MYANMAR,
    "Nabataean" to NABATAEAN,
    "Nag_Mundari" to NAG_MUNDARI,
    "Nandinagari" to NANDINAGARI,
    "New_Tai_Lue" to NEW_TAI_LUE,
    "Newa" to NEWA,
    "Nko" to NKO,
    "Nushu" to NUSHU,
    "Nyiakeng_Puachue_Hmong" to NYIAKENG_PUACHUE_HMONG,
    "Ogham" to OGHAM,
    "Ol_Chiki" to OL_CHIKI,
    "Ol_Onal" to OL_ONAL,
    "Old_Hungarian" to OLD_HUNGARIAN,
    "Old_Italic" to OLD_ITALIC,
    "Old_North_Arabian" to OLD_NORTH_ARABIAN,
    "Old_Permic" to OLD_PERMIC,
    "Old_Persian" to OLD_PERSIAN,
    "Old_Sogdian" to OLD_SOGDIAN,
    "Old_South_Arabian" to OLD_SOUTH_ARABIAN,
    "Old_Turkic" to OLD_TURKIC,
    "Old_Uyghur" to OLD_UYGHUR,
    "Oriya" to ORIYA,
    "Osage" to OSAGE,
    "Osmanya" to OSMANYA,
    "Pahawh_Hmong" to PAHAWH_HMONG,
    "Palmyrene" to PALMYRENE,
    "Pau_Cin_Hau" to PAU_CIN_HAU,
    "Phags_Pa" to PHAGS_PA,
    "Phoenician" to PHOENICIAN,
    "Psalter_Pahlavi" to PSALTER_PAHLAVI,
    "Rejang" to REJANG,
    "Runic" to RUNIC,
    "Samaritan" to SAMARITAN,
    "Saurashtra" to SAURASHTRA,
    "Sharada" to SHARADA,
    "Shavian" to SHAVIAN,
    "Siddham" to SIDDHAM,
    "SignWriting" to SIGNWRITING,
    "Sinhala" to SINHALA,
    "Sogdian" to SOGDIAN,
    "Sora_Sompeng" to SORA_SOMPENG,
    "Soyombo" to SOYOMBO,
    "Sundanese" to SUNDANESE,
    "Sunuwar" to SUNUWAR,
    "Syloti_Nagri" to SYLOTI_NAGRI,
    "Syriac" to SYRIAC,
    "Tagalog" to TAGALOG,
    "Tagbanwa" to TAGBANWA,
    "Tai_Le" to TAI_LE,
    "Tai_Tham" to TAI_THAM,
    "Tai_Viet" to TAI_VIET,
    "Takri" to TAKRI,
    "Tamil" to TAMIL,
    "Tangsa" to TANGSA,
    "Tangut" to TANGUT,
    "Telugu" to TELUGU,
    "Thaana" to THAANA,
    "Thai" to THAI,
    "Tibetan" to TIBETAN,
    "Tifinagh" to TIFINAGH,
    "Tirhuta" to TIRHUTA,
    "Todhri" to TODHRI,
    "Toto" to TOTO,
    "Tulu_Tigalari" to TULU_TIGALARI,
    "Ugaritic" to UGARITIC,
    "Vai" to VAI,
    "Vithkuqi" to VITHKUQI,
    "Wancho" to WANCHO,
    "Warang_Citi" to WARANG_CITI,
    "Yezidi" to YEZIDI,
    "Yi" to YI,
    "Zanabazar_Square" to ZANABAZAR_SQUARE,
)

